package emotionalsongs;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *@hidden
 * @author natanaild
 */
public class ConsultaRepositoryMenu extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaRepositoryMenuButtonPanel
     */
    public ConsultaRepositoryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaRepositoryWestButtonsMenuPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        CercaTitolo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CercaAutoreAnno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(160, 600));

        ConsultaRepositoryWestButtonsMenuPanel.setPreferredSize(new java.awt.Dimension(160, 600));
        ConsultaRepositoryWestButtonsMenuPanel.setLayout(new java.awt.GridLayout(8, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("emotionalsongs/Bundle"); // NOI18N
        CercaTitolo.setText(bundle.getString("ConsultaRepositoryMenu.CercaTitolo.text")); // NOI18N
        jPanel1.add(CercaTitolo);

        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        CercaAutoreAnno.setText(bundle.getString("ConsultaRepositoryMenu.CercaAutoreAnno.text")); // NOI18N
        jPanel2.add(CercaAutoreAnno);

        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton3.setText(bundle.getString("ConsultaRepositoryMenu.jButton3.text")); // NOI18N
        jPanel3.add(jButton3);

        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setText(bundle.getString("ConsultaRepositoryMenu.jButton4.text")); // NOI18N
        jPanel4.add(jButton4);

        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jButton5.setText(bundle.getString("ConsultaRepositoryMenu.jButton5.text")); // NOI18N
        jPanel5.add(jButton5);

        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        ConsultaRepositoryWestButtonsMenuPanel.add(jPanel8);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 160, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(ConsultaRepositoryWestButtonsMenuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 600, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(ConsultaRepositoryWestButtonsMenuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CercaAutoreAnno;
    private javax.swing.JButton CercaTitolo;
    private javax.swing.JPanel ConsultaRepositoryWestButtonsMenuPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
