/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package emotionalsongs;

/**
 *
 * @author big
 */
public class GUIPlaylistsMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form GUIPlaylistsMainPanel
     */
    
    User user;
    PlayListsManager playListsManager = EMOTIONALSONGS.playListsManager;
    public GUIPlaylistsMainPanel(User user,PlayListsManager playListsManager) {
        EngineSearcher searcher = new EngineSearcher();
        this.user = user;
        initComponents();
        //this.playListsManager = playListsManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        leftPanel.setPreferredSize(new java.awt.Dimension(200, 300));
        leftPanel.setLayout(new java.awt.BorderLayout());
        add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setLayout(new java.awt.BorderLayout());
        add(rightPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    void setLeftPanel(GUIPlaylistsSubLeftPanel left){
        leftPanel.add(left);
        revalidate();
        repaint();
    }
    
    void setRightPanel(GUIPlaylistsSubRightPanel right){
        rightPanel.add(right);
        revalidate();
        repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
