
package emotionalsongs;

import java.awt.*;
import java.io.*;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author big
 */
public class GUIPlaylistCreationFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUIPlaylistCreationFrame
     */
    
    public GUIPlaylistCreationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new JPanel(){
            @Override
            protected void paintComponent(Graphics g){
                Graphics g2 = g.create();
                g2.drawImage(Utilities.regBG.getImage(), 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        selectPlaylistNamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playlistNameTextField = new javax.swing.JTextField();
        createButtonPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        selectedSongsPanel = new javax.swing.JPanel();
        addSongsPanel = new javax.swing.JPanel();
        searchSongToAddButton = new javax.swing.JToggleButton();
        changingPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedSongScrollViewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        mainPanel.setOpaque(true);
        mainPanel.setLayout(new java.awt.BorderLayout());

        selectPlaylistNamePanel.setOpaque(false);
        selectPlaylistNamePanel.setPreferredSize(new java.awt.Dimension(700, 50));
        selectPlaylistNamePanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome della nuova playlist:    ");
        selectPlaylistNamePanel.add(jLabel1, new java.awt.GridBagConstraints());

        playlistNameTextField.setText("newPlaylist");
        playlistNameTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        playlistNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistNameTextFieldActionPerformed(evt);
            }
        });
        selectPlaylistNamePanel.add(playlistNameTextField, new java.awt.GridBagConstraints());

        mainPanel.add(selectPlaylistNamePanel, java.awt.BorderLayout.PAGE_START);

        createButtonPanel.setOpaque(false);
        createButtonPanel.setPreferredSize(new java.awt.Dimension(120, 40));
        java.awt.GridBagLayout createButtonPanelLayout = new java.awt.GridBagLayout();
        createButtonPanelLayout.columnWidths = new int[] {0, 80, 0};
        createButtonPanelLayout.rowHeights = new int[] {0};
        createButtonPanel.setLayout(createButtonPanelLayout);

        createButton.setText("jButton2");
        createButton.setPreferredSize(new java.awt.Dimension(120, 40));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        createButtonPanel.add(createButton, gridBagConstraints);

        backButton.setText("jButton3");
        backButton.setPreferredSize(new java.awt.Dimension(120, 40));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        createButtonPanel.add(backButton, gridBagConstraints);

        mainPanel.add(createButtonPanel, java.awt.BorderLayout.PAGE_END);

        selectedSongsPanel.setOpaque(false);
        selectedSongsPanel.setLayout(new java.awt.BorderLayout());

        addSongsPanel.setOpaque(false);
        addSongsPanel.setPreferredSize(new java.awt.Dimension(700, 40));
        addSongsPanel.setLayout(new java.awt.BorderLayout());

        searchSongToAddButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                searchSongToAddButtonStateChanged(evt);
            }
        });
        searchSongToAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSongToAddButtonActionPerformed(evt);
            }
        });
        addSongsPanel.add(searchSongToAddButton, java.awt.BorderLayout.CENTER);

        selectedSongsPanel.add(addSongsPanel, java.awt.BorderLayout.PAGE_END);

        changingPanel.setOpaque(false);
        changingPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        selectedSongScrollViewPanel.setBackground(new Color(0,0,0,160));
        selectedSongScrollViewPanel.setOpaque(false);
        selectedSongScrollViewPanel.setPreferredSize(new Dimension(jScrollPane1.getWidth(),30*EMOTIONALSONGS.playListsManager.getNumberOfSongToAdd()));
        for(int i = 0;i<EMOTIONALSONGS.playListsManager.getNumberOfSongToAdd();i++){
            selectedSongScrollViewPanel.add(EMOTIONALSONGS.playListsManager.getSongToAdd(i).buildSimpleRepresentation());
        }
        selectedSongScrollViewPanel.setLayout(new java.awt.GridLayout(EMOTIONALSONGS.playListsManager.getNumberOfSongToAdd(), 1));
        jScrollPane1.setViewportView(selectedSongScrollViewPanel);

        changingPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        selectedSongsPanel.add(changingPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(selectedSongsPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playlistNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistNameTextFieldActionPerformed
        
    }//GEN-LAST:event_playlistNameTextFieldActionPerformed

    private void searchSongToAddButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_searchSongToAddButtonStateChanged
        
            try {
                changingPanel.removeAll();
                if(searchSongToAddButton.isSelected()) changingPanel.add(new GUIPlaylistSongSearchPanel(EMOTIONALSONGS.playListsManager));
                else changingPanel.add(new GUIPlaylistSongToAddViewPanel(EMOTIONALSONGS.playListsManager));
                revalidate();
                repaint();
                
            } catch (IOException ex) {
                Logger.getLogger(GUIPlaylistCreationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_searchSongToAddButtonStateChanged

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        close();
    }//GEN-LAST:event_backButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        EMOTIONALSONGS.playListsManager.setTitlePlaylist(playlistNameTextField.getText().isBlank()?"newPlaylist":playlistNameTextField.getText());
        EMOTIONALSONGS.playListsManager.registraPlaylist();
        close();
    }//GEN-LAST:event_createButtonActionPerformed

    private void searchSongToAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSongToAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSongToAddButtonActionPerformed

    
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPlaylistCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPlaylistCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPlaylistCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPlaylistCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPlaylistCreationFrame().setVisible(true);
            }
        });
    }
    
    public void close() {
        this.dispose();
        EMOTIONALSONGS.playListsManager.eraseSongToAdd();
        EMOTIONALSONGS.playListsManager.eraseTitlePlaylist();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addSongsPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel changingPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel createButtonPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField playlistNameTextField;
    private javax.swing.JToggleButton searchSongToAddButton;
    private javax.swing.JPanel selectPlaylistNamePanel;
    private javax.swing.JPanel selectedSongScrollViewPanel;
    private javax.swing.JPanel selectedSongsPanel;
    // End of variables declaration//GEN-END:variables
}
