
package emotionalsongs;

import java.awt.*;

/**
 *
 * @author big
 */
public class GUIPlaylistSongToAddViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form GUIPlaylistSongToAddViewPanel
     */
    PlayListsManager playlistsManager = EMOTIONALSONGS.playListsManager;
    public GUIPlaylistSongToAddViewPanel(PlayListsManager playlistsManager) {
        //this.playlistsManager = playlistsManager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        innerScroll = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        innerScroll.setOpaque(false);
        innerScroll.setPreferredSize(new Dimension(jScrollPane1.getWidth(),30*playlistsManager.getNumberOfSongToAdd()));
        for(int i = 0;i<playlistsManager.getNumberOfSongToAdd();i++){
            innerScroll.add(playlistsManager.getSongToAdd(i).buildSimpleRepresentation());
        }
        innerScroll.setLayout(new java.awt.GridLayout(playlistsManager.getNumberOfSongToAdd(), 1));
        jScrollPane1.setViewportView(innerScroll);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel innerScroll;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
