
package emotionalsongs;

import java.awt.*;

/**
 *
 * @author big
 */
public class GUIPlaylistsSubRightPanel extends javax.swing.JPanel {

    /**
     * Creates new form GUIPlaylistsSubRightPanel
     */
    Playlist correlatedPlaylist;
    
    public GUIPlaylistsSubRightPanel(Playlist playlist) {
        correlatedPlaylist = playlist;
        initComponents();
        EngineSearcher searcher = new EngineSearcher();
        for (int i = 0; i < playlist.getSize(); i++) {
            songsPanel.add(new GUIBranoViewVotePanel(searcher.searchBranoTag(EMOTIONALSONGS.REPOSITORY, correlatedPlaylist.get(i))));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        songsPanel = new javax.swing.JPanel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(700, 600));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        songsPanel.setOpaque(false);
        songsPanel.setPreferredSize(new Dimension(jScrollPane1.getWidth(),jScrollPane1.getHeight()>30*correlatedPlaylist.getSize()?jScrollPane1.getHeight():30*correlatedPlaylist.getSize()));
        songsPanel.setLayout(new java.awt.GridLayout(correlatedPlaylist.getSize(), 1));
        jScrollPane1.setViewportView(songsPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel songsPanel;
    // End of variables declaration//GEN-END:variables

    void addToScroll(GUIBranoViewPanel guiBranoViewPanel) {
        songsPanel.add(guiBranoViewPanel);
    }
}
