/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package emotionalsongs.GUIElements;

/**
 *
 * @author natanaild
 */
public class RegistrazionePanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrazionePanel
     */
    public RegistrazionePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        RegistrazioneLabelPanel = new javax.swing.JPanel();
        RegistrazioneLabel = new javax.swing.JLabel();
        NomePanel = new javax.swing.JPanel();
        NomeLabel = new javax.swing.JLabel();
        NomeField = new javax.swing.JTextField();
        CognomePanel = new javax.swing.JPanel();
        CognomeLabel = new javax.swing.JLabel();
        CognomeField = new javax.swing.JTextField();
        CFPanel = new javax.swing.JPanel();
        CFLabel = new javax.swing.JLabel();
        CFField = new javax.swing.JTextField();
        CFCheckLabel = new javax.swing.JLabel();
        DataNascitaPanel = new javax.swing.JPanel();
        DataNascitaLabel = new javax.swing.JLabel();
        DataNascitaField = new javax.swing.JTextField();
        IndirizzoPanel = new javax.swing.JPanel();
        IndirizzoLabel = new javax.swing.JLabel();
        IndirizzoField = new javax.swing.JTextField();
        UserIDPanel = new javax.swing.JPanel();
        UserIDLabel = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        UserIDCheckLabel = new javax.swing.JLabel();
        EmailPanel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        EmailCorrettoLabel = new javax.swing.JLabel();
        PasswordPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordCheckLabel = new javax.swing.JLabel();
        PasswordCheckField = new javax.swing.JPasswordField();
        PasswordNonValidaLabel = new javax.swing.JLabel();
        PasswordNonCoincidonoLabel = new javax.swing.JLabel();
        RegistrazioneButtonsPanel = new javax.swing.JPanel();
        RegistratiButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AnnullaButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new java.awt.GridLayout(10, 1));

        RegistrazioneLabelPanel.setLayout(new java.awt.GridLayout(1, 0));

        RegistrazioneLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        RegistrazioneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("emotionalsongs/GUIElements/Bundle"); // NOI18N
        RegistrazioneLabel.setText(bundle.getString("RegistrazionePanel.RegistrazioneLabel.text")); // NOI18N
        RegistrazioneLabelPanel.add(RegistrazioneLabel);

        add(RegistrazioneLabelPanel);

        NomePanel.setLayout(new java.awt.GridBagLayout());

        NomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeLabel.setText(bundle.getString("RegistrazionePanel.NomeLabel.text")); // NOI18N
        NomeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        NomePanel.add(NomeLabel, gridBagConstraints);

        NomeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NomeField.setText(bundle.getString("RegistrazionePanel.NomeField.text")); // NOI18N
        NomeField.setPreferredSize(new java.awt.Dimension(300, 23));
        NomePanel.add(NomeField, new java.awt.GridBagConstraints());

        add(NomePanel);

        CognomePanel.setLayout(new java.awt.GridBagLayout());

        CognomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CognomeLabel.setText(bundle.getString("RegistrazionePanel.CognomeLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        CognomePanel.add(CognomeLabel, gridBagConstraints);

        CognomeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CognomeField.setText(bundle.getString("RegistrazionePanel.CognomeField.text")); // NOI18N
        CognomeField.setPreferredSize(new java.awt.Dimension(300, 23));
        CognomePanel.add(CognomeField, new java.awt.GridBagConstraints());

        add(CognomePanel);

        CFPanel.setLayout(new java.awt.GridBagLayout());

        CFLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CFLabel.setText(bundle.getString("RegistrazionePanel.CFLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        CFPanel.add(CFLabel, gridBagConstraints);

        CFField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CFField.setText(bundle.getString("RegistrazionePanel.CFField.text")); // NOI18N
        CFField.setPreferredSize(new java.awt.Dimension(300, 23));
        CFPanel.add(CFField, new java.awt.GridBagConstraints());

        CFCheckLabel.setForeground(new java.awt.Color(255, 0, 0));
        CFCheckLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CFCheckLabel.setLabelFor(CFField);
        CFCheckLabel.setText(bundle.getString("RegistrazionePanel.CFCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        CFPanel.add(CFCheckLabel, gridBagConstraints);

        add(CFPanel);

        DataNascitaPanel.setLayout(new java.awt.GridBagLayout());

        DataNascitaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DataNascitaLabel.setText(bundle.getString("RegistrazionePanel.DataNascitaLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        DataNascitaPanel.add(DataNascitaLabel, gridBagConstraints);

        DataNascitaField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DataNascitaField.setText(bundle.getString("RegistrazionePanel.DataNascitaField.text")); // NOI18N
        DataNascitaField.setPreferredSize(new java.awt.Dimension(130, 23));
        DataNascitaPanel.add(DataNascitaField, new java.awt.GridBagConstraints());

        add(DataNascitaPanel);

        IndirizzoPanel.setLayout(new java.awt.GridBagLayout());

        IndirizzoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IndirizzoLabel.setText(bundle.getString("RegistrazionePanel.IndirizzoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        IndirizzoPanel.add(IndirizzoLabel, gridBagConstraints);

        IndirizzoField.setText(bundle.getString("RegistrazionePanel.IndirizzoField.text")); // NOI18N
        IndirizzoField.setPreferredSize(new java.awt.Dimension(400, 23));
        IndirizzoPanel.add(IndirizzoField, new java.awt.GridBagConstraints());

        add(IndirizzoPanel);

        UserIDPanel.setLayout(new java.awt.GridBagLayout());

        UserIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserIDLabel.setText(bundle.getString("RegistrazionePanel.UserIDLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        UserIDPanel.add(UserIDLabel, gridBagConstraints);

        UserIDField.setText(bundle.getString("RegistrazionePanel.UserIDField.text")); // NOI18N
        UserIDField.setPreferredSize(new java.awt.Dimension(300, 23));
        UserIDPanel.add(UserIDField, new java.awt.GridBagConstraints());

        UserIDCheckLabel.setForeground(new java.awt.Color(255, 0, 0));
        UserIDCheckLabel.setText(bundle.getString("RegistrazionePanel.UserIDCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        UserIDPanel.add(UserIDCheckLabel, gridBagConstraints);

        add(UserIDPanel);

        EmailPanel.setLayout(new java.awt.GridBagLayout());

        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailLabel.setText(bundle.getString("RegistrazionePanel.EmailLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        EmailPanel.add(EmailLabel, gridBagConstraints);

        EmailField.setText(bundle.getString("RegistrazionePanel.EmailField.text")); // NOI18N
        EmailField.setPreferredSize(new java.awt.Dimension(300, 23));
        EmailPanel.add(EmailField, new java.awt.GridBagConstraints());

        EmailCorrettoLabel.setForeground(new java.awt.Color(255, 0, 0));
        EmailCorrettoLabel.setText(bundle.getString("RegistrazionePanel.EmailCorrettoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        EmailPanel.add(EmailCorrettoLabel, gridBagConstraints);

        add(EmailPanel);

        PasswordPanel.setLayout(new java.awt.GridBagLayout());

        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText(bundle.getString("RegistrazionePanel.PasswordLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        PasswordPanel.add(PasswordLabel, gridBagConstraints);

        PasswordField.setText(bundle.getString("RegistrazionePanel.PasswordField.text")); // NOI18N
        PasswordField.setPreferredSize(new java.awt.Dimension(200, 23));
        PasswordPanel.add(PasswordField, new java.awt.GridBagConstraints());

        PasswordCheckLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordCheckLabel.setText(bundle.getString("RegistrazionePanel.PasswordCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        PasswordPanel.add(PasswordCheckLabel, gridBagConstraints);

        PasswordCheckField.setText(bundle.getString("RegistrazionePanel.PasswordCheckField.text")); // NOI18N
        PasswordCheckField.setPreferredSize(new java.awt.Dimension(200, 23));
        PasswordPanel.add(PasswordCheckField, new java.awt.GridBagConstraints());

        PasswordNonValidaLabel.setForeground(new java.awt.Color(255, 0, 0));
        PasswordNonValidaLabel.setText(bundle.getString("RegistrazionePanel.PasswordNonValidaLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        PasswordPanel.add(PasswordNonValidaLabel, gridBagConstraints);

        PasswordNonCoincidonoLabel.setForeground(new java.awt.Color(255, 0, 0));
        PasswordNonCoincidonoLabel.setText(bundle.getString("RegistrazionePanel.PasswordNonCoincidonoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        PasswordPanel.add(PasswordNonCoincidonoLabel, gridBagConstraints);

        add(PasswordPanel);

        RegistrazioneButtonsPanel.setLayout(new java.awt.GridBagLayout());

        RegistratiButton.setText(bundle.getString("RegistrazionePanel.RegistratiButton.text")); // NOI18N
        RegistrazioneButtonsPanel.add(RegistratiButton, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        RegistrazioneButtonsPanel.add(jPanel1, gridBagConstraints);

        AnnullaButton.setText(bundle.getString("RegistrazionePanel.AnnullaButton.text")); // NOI18N
        RegistrazioneButtonsPanel.add(AnnullaButton, new java.awt.GridBagConstraints());

        add(RegistrazioneButtonsPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullaButton;
    private javax.swing.JLabel CFCheckLabel;
    private javax.swing.JTextField CFField;
    private javax.swing.JLabel CFLabel;
    private javax.swing.JPanel CFPanel;
    private javax.swing.JTextField CognomeField;
    private javax.swing.JLabel CognomeLabel;
    private javax.swing.JPanel CognomePanel;
    private javax.swing.JTextField DataNascitaField;
    private javax.swing.JLabel DataNascitaLabel;
    private javax.swing.JPanel DataNascitaPanel;
    private javax.swing.JLabel EmailCorrettoLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel EmailPanel;
    private javax.swing.JTextField IndirizzoField;
    private javax.swing.JLabel IndirizzoLabel;
    private javax.swing.JPanel IndirizzoPanel;
    private javax.swing.JTextField NomeField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JPanel NomePanel;
    private javax.swing.JPasswordField PasswordCheckField;
    private javax.swing.JLabel PasswordCheckLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordNonCoincidonoLabel;
    private javax.swing.JLabel PasswordNonValidaLabel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JButton RegistratiButton;
    private javax.swing.JPanel RegistrazioneButtonsPanel;
    private javax.swing.JLabel RegistrazioneLabel;
    private javax.swing.JPanel RegistrazioneLabelPanel;
    private javax.swing.JLabel UserIDCheckLabel;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JPanel UserIDPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
