/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package emotionalsongs;

import java.io.*;

/**
 * @hidden
 * @author natanaild
 */
public class RegistrationPanel extends javax.swing.JPanel {
    String userId,nome,cognome,cf,indirizzo,email,pswd,dataNascita;

    /**
     * Creates new form RegistrazionePanel
     */
    public RegistrationPanel() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        RegistrazioneLabelPanel = new javax.swing.JPanel();
        RegistrazioneLabel = new javax.swing.JLabel();
        NomePanel = new javax.swing.JPanel();
        NomeLabel = new javax.swing.JLabel();
        NomeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CognomePanel = new javax.swing.JPanel();
        CognomeLabel = new javax.swing.JLabel();
        CognomeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CFPanel = new javax.swing.JPanel();
        CFLabel = new javax.swing.JLabel();
        CFField = new javax.swing.JTextField();
        CFCheckLabel = new javax.swing.JLabel();
        DataNascitaPanel = new javax.swing.JPanel();
        DataNascitaLabel = new javax.swing.JLabel();
        DataNascitaField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IndirizzoPanel = new javax.swing.JPanel();
        IndirizzoLabel = new javax.swing.JLabel();
        IndirizzoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        UserIDPanel = new javax.swing.JPanel();
        UserIDLabel = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        UserIDCheckLabel = new javax.swing.JLabel();
        EmailPanel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        EmailCorrettoLabel = new javax.swing.JLabel();
        PasswordPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordCheckLabel = new javax.swing.JLabel();
        PasswordCheckField = new javax.swing.JPasswordField();
        PasswordNonValidaLabel = new javax.swing.JLabel();
        PasswordNonCoincidonoLabel = new javax.swing.JLabel();
        RegistrazioneButtonsPanel = new javax.swing.JPanel();
        RegistratiButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AnnullaButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new java.awt.GridLayout(10, 1));

        RegistrazioneLabelPanel.setLayout(new java.awt.GridLayout(1, 0));

        RegistrazioneLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        RegistrazioneLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrazioneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("emotionalsongs/GUIElements/Bundle"); // NOI18N
        RegistrazioneLabel.setText(bundle.getString("RegistrationPanel.RegistrazioneLabel.text")); // NOI18N
        RegistrazioneLabelPanel.add(RegistrazioneLabel);

        add(RegistrazioneLabelPanel);

        NomePanel.setLayout(new java.awt.GridBagLayout());

        NomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        NomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeLabel.setText(bundle.getString("RegistrationPanel.NomeLabel.text")); // NOI18N
        NomeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        NomePanel.add(NomeLabel, gridBagConstraints);

        NomeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NomeField.setText(bundle.getString("RegistrationPanel.NomeField.text")); // NOI18N
        NomeField.setPreferredSize(new java.awt.Dimension(300, 23));
        NomePanel.add(NomeField, new java.awt.GridBagConstraints());

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("emotionalsongs/Bundle"); // NOI18N
        jLabel1.setText(bundle1.getString("RegistrationPanel.jLabel1.text")); // NOI18N
        NomePanel.add(jLabel1, new java.awt.GridBagConstraints());
        jLabel1.getAccessibleContext().setAccessibleName(bundle1.getString("RegistrationPanel.jLabel1.AccessibleContext.accessibleName")); // NOI18N

        add(NomePanel);

        CognomePanel.setLayout(new java.awt.GridBagLayout());

        CognomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        CognomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CognomeLabel.setText(bundle.getString("RegistrationPanel.CognomeLabel.text")); // NOI18N
        CognomePanel.add(CognomeLabel, new java.awt.GridBagConstraints());

        CognomeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CognomeField.setText(bundle.getString("RegistrationPanel.CognomeField.text")); // NOI18N
        CognomeField.setPreferredSize(new java.awt.Dimension(300, 23));
        CognomePanel.add(CognomeField, new java.awt.GridBagConstraints());

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText(bundle1.getString("RegistrationPanel.jLabel2.text")); // NOI18N
        CognomePanel.add(jLabel2, new java.awt.GridBagConstraints());
        jLabel2.getAccessibleContext().setAccessibleName(bundle1.getString("RegistrationPanel.jLabel2.AccessibleContext.accessibleName")); // NOI18N

        add(CognomePanel);

        CFPanel.setLayout(new java.awt.GridBagLayout());

        CFLabel.setForeground(new java.awt.Color(255, 255, 255));
        CFLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CFLabel.setText(bundle.getString("RegistrationPanel.CFLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        CFPanel.add(CFLabel, gridBagConstraints);

        CFField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CFField.setText(bundle.getString("RegistrationPanel.CFField.text")); // NOI18N
        CFField.setPreferredSize(new java.awt.Dimension(300, 23));
        CFPanel.add(CFField, new java.awt.GridBagConstraints());

        CFCheckLabel.setForeground(new java.awt.Color(255, 0, 0));
        CFCheckLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CFCheckLabel.setLabelFor(CFField);
        CFCheckLabel.setText(bundle.getString("RegistrationPanel.CFCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        CFPanel.add(CFCheckLabel, gridBagConstraints);

        add(CFPanel);

        DataNascitaPanel.setLayout(new java.awt.GridBagLayout());

        DataNascitaLabel.setForeground(new java.awt.Color(255, 255, 255));
        DataNascitaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DataNascitaLabel.setText(bundle.getString("RegistrationPanel.DataNascitaLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        DataNascitaPanel.add(DataNascitaLabel, gridBagConstraints);

        DataNascitaField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DataNascitaField.setText(bundle.getString("RegistrationPanel.DataNascitaField.text")); // NOI18N
        DataNascitaField.setPreferredSize(new java.awt.Dimension(130, 23));
        DataNascitaPanel.add(DataNascitaField, new java.awt.GridBagConstraints());

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText(bundle1.getString("RegistrationPanel.jLabel3.text")); // NOI18N
        DataNascitaPanel.add(jLabel3, new java.awt.GridBagConstraints());
        jLabel3.getAccessibleContext().setAccessibleName(bundle1.getString("RegistrationPanel.jLabel3.AccessibleContext.accessibleName")); // NOI18N

        add(DataNascitaPanel);

        IndirizzoPanel.setLayout(new java.awt.GridBagLayout());

        IndirizzoLabel.setForeground(new java.awt.Color(255, 255, 255));
        IndirizzoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IndirizzoLabel.setText(bundle.getString("RegistrationPanel.IndirizzoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        IndirizzoPanel.add(IndirizzoLabel, gridBagConstraints);

        IndirizzoField.setText(bundle.getString("RegistrationPanel.IndirizzoField.text")); // NOI18N
        IndirizzoField.setPreferredSize(new java.awt.Dimension(400, 23));
        IndirizzoPanel.add(IndirizzoField, new java.awt.GridBagConstraints());

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText(bundle1.getString("RegistrationPanel.jLabel4.text")); // NOI18N
        IndirizzoPanel.add(jLabel4, new java.awt.GridBagConstraints());
        jLabel4.getAccessibleContext().setAccessibleName(bundle1.getString("RegistrationPanel.jLabel4.AccessibleContext.accessibleName")); // NOI18N

        add(IndirizzoPanel);

        UserIDPanel.setLayout(new java.awt.GridBagLayout());

        UserIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserIDLabel.setText(bundle.getString("RegistrationPanel.UserIDLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        UserIDPanel.add(UserIDLabel, gridBagConstraints);

        UserIDField.setText(bundle.getString("RegistrationPanel.UserIDField.text")); // NOI18N
        UserIDField.setPreferredSize(new java.awt.Dimension(300, 23));
        UserIDPanel.add(UserIDField, new java.awt.GridBagConstraints());

        UserIDCheckLabel.setForeground(new java.awt.Color(255, 0, 0));
        UserIDCheckLabel.setText(bundle.getString("RegistrationPanel.UserIDCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        UserIDPanel.add(UserIDCheckLabel, gridBagConstraints);

        add(UserIDPanel);

        EmailPanel.setLayout(new java.awt.GridBagLayout());

        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailLabel.setText(bundle.getString("RegistrationPanel.EmailLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        EmailPanel.add(EmailLabel, gridBagConstraints);

        EmailField.setText(bundle.getString("RegistrationPanel.EmailField.text")); // NOI18N
        EmailField.setPreferredSize(new java.awt.Dimension(300, 23));
        EmailPanel.add(EmailField, new java.awt.GridBagConstraints());

        EmailCorrettoLabel.setForeground(new java.awt.Color(255, 0, 0));
        EmailCorrettoLabel.setText(bundle.getString("RegistrationPanel.EmailCorrettoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        EmailPanel.add(EmailCorrettoLabel, gridBagConstraints);

        add(EmailPanel);

        PasswordPanel.setLayout(new java.awt.GridBagLayout());

        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText(bundle.getString("RegistrationPanel.PasswordLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        PasswordPanel.add(PasswordLabel, gridBagConstraints);

        PasswordField.setText(bundle.getString("RegistrationPanel.PasswordField.text")); // NOI18N
        PasswordField.setPreferredSize(new java.awt.Dimension(200, 23));
        PasswordPanel.add(PasswordField, new java.awt.GridBagConstraints());

        PasswordCheckLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordCheckLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordCheckLabel.setText(bundle.getString("RegistrationPanel.PasswordCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        PasswordPanel.add(PasswordCheckLabel, gridBagConstraints);

        PasswordCheckField.setText(bundle.getString("RegistrationPanel.PasswordCheckField.text")); // NOI18N
        PasswordCheckField.setPreferredSize(new java.awt.Dimension(200, 23));
        PasswordPanel.add(PasswordCheckField, new java.awt.GridBagConstraints());

        PasswordNonValidaLabel.setForeground(new java.awt.Color(255, 0, 0));
        PasswordNonValidaLabel.setText(bundle.getString("RegistrationPanel.PasswordNonValidaLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        PasswordPanel.add(PasswordNonValidaLabel, gridBagConstraints);

        PasswordNonCoincidonoLabel.setForeground(new java.awt.Color(255, 0, 0));
        PasswordNonCoincidonoLabel.setText(bundle.getString("RegistrationPanel.PasswordNonCoincidonoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        PasswordPanel.add(PasswordNonCoincidonoLabel, gridBagConstraints);

        add(PasswordPanel);

        RegistrazioneButtonsPanel.setLayout(new java.awt.GridBagLayout());

        RegistratiButton.setText(bundle.getString("RegistrationPanel.RegistratiButton.text")); // NOI18N
        RegistratiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistratiButtonActionPerformed(evt);
            }
        });
        RegistrazioneButtonsPanel.add(RegistratiButton, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        RegistrazioneButtonsPanel.add(jPanel1, gridBagConstraints);

        AnnullaButton.setText(bundle.getString("RegistrationPanel.AnnullaButton.text")); // NOI18N
        RegistrazioneButtonsPanel.add(AnnullaButton, new java.awt.GridBagConstraints());

        add(RegistrazioneButtonsPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistratiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistratiButtonActionPerformed
        RegistrationPerformer engine = new RegistrationPerformer(this);
        try {
            engine.registraNuovoUtente(userId, NomeField.getText(), CognomeField.getText(), CFField.getText(), IndirizzoField.getText(), EmailField.getText(), String.valueOf(PasswordField.getPassword()), DataNascitaField.getText());
        } catch (IOException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_RegistratiButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullaButton;
    public javax.swing.JLabel CFCheckLabel;
    private javax.swing.JTextField CFField;
    private javax.swing.JLabel CFLabel;
    private javax.swing.JPanel CFPanel;
    private javax.swing.JTextField CognomeField;
    private javax.swing.JLabel CognomeLabel;
    private javax.swing.JPanel CognomePanel;
    private javax.swing.JTextField DataNascitaField;
    private javax.swing.JLabel DataNascitaLabel;
    private javax.swing.JPanel DataNascitaPanel;
    public javax.swing.JLabel EmailCorrettoLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel EmailPanel;
    private javax.swing.JTextField IndirizzoField;
    private javax.swing.JLabel IndirizzoLabel;
    private javax.swing.JPanel IndirizzoPanel;
    private javax.swing.JTextField NomeField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JPanel NomePanel;
    private javax.swing.JPasswordField PasswordCheckField;
    private javax.swing.JLabel PasswordCheckLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordNonCoincidonoLabel;
    public javax.swing.JLabel PasswordNonValidaLabel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JButton RegistratiButton;
    private javax.swing.JPanel RegistrazioneButtonsPanel;
    private javax.swing.JLabel RegistrazioneLabel;
    private javax.swing.JPanel RegistrazioneLabelPanel;
    public javax.swing.JLabel UserIDCheckLabel;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JPanel UserIDPanel;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
