/*
 * Luca Bolelli - 749137 - VA
 * Natanail Danailov Danailov - 739887 - VA
 * Riccardo Rosarin - 749914 - VA
 * Eleonora Macchi - 748736 - VA
 */



package emotionalsongs.gui.songs_judgements;

import emotionalsongs.*;
import emotionalsongs.basic_structures.*;
import emotionalsongs.data_structures.*;
import emotionalsongs.dialogs.*;
import emotionalsongs.engines.*;
import emotionalsongs.gui.allerter.*;
import emotionalsongs.gui.playlists.*;
import javax.swing.*;

/**
 * Classi le cui istanze permettono di esprimere giudizi emozionali.
 */
public class SongJudgementForm extends javax.swing.JPanel {
    
    /**
     * Crea il form per creare un giudizio emozionale relativo alla canzone rappresentata dal tag passato
     * come argomento ed al utente rappresentato dal id passato come argomento.
     * @param loggedUserId Id del utente che effettua il giudizio emozionale.
     * @param songToVoteTag Tag della canzone giudicata.
     * @param callerComponent Pannello da cui la funzione è stata chiamata.
     */
    public SongJudgementForm(String loggedUserId,String songToVoteTag,SongPanel callerComponent,JFrame container) {
        this.loggedUserId = loggedUserId;
        this.songToVoteTag = songToVoteTag;
        this.callerComponent = callerComponent;
        this.container = container;
        EngineSearcher searcher = new EngineSearcher();
        songUnderVotation = searcher.searchBySongTag(Repository.getInstance(), songToVoteTag);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        innerPanel = new javax.swing.JPanel();
        amazementPane = new javax.swing.JPanel();
        GeneralDescriptionPane = new javax.swing.JPanel();
        songDataLabel = new javax.swing.JLabel();
        mainAmazementEmotionPane = new javax.swing.JPanel();
        amazementTitle = new javax.swing.JLabel();
        amazementDescription = new javax.swing.JLabel();
        amazementMarksPanel = new javax.swing.JPanel();
        amazementMark1 = new javax.swing.JRadioButton();
        amazementMark2 = new javax.swing.JRadioButton();
        amazementMark3 = new javax.swing.JRadioButton();
        amazementMark4 = new javax.swing.JRadioButton();
        amazementMark5 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        amazementNotes = new javax.swing.JTextArea();
        solemnityPane = new javax.swing.JPanel();
        solemnityTitle = new javax.swing.JLabel();
        solemnityDescription = new javax.swing.JLabel();
        solemnityMarksPane = new javax.swing.JPanel();
        solemnityMark1 = new javax.swing.JRadioButton();
        solemnityMark2 = new javax.swing.JRadioButton();
        solemnityMark3 = new javax.swing.JRadioButton();
        solemnityMark4 = new javax.swing.JRadioButton();
        solemnityMark5 = new javax.swing.JRadioButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        solemnityNotes = new javax.swing.JTextArea();
        tendernessPane = new javax.swing.JPanel();
        tendernessTitle = new javax.swing.JLabel();
        tendernessDescription = new javax.swing.JLabel();
        tendernessMarksPanel = new javax.swing.JPanel();
        tendernessMark1 = new javax.swing.JRadioButton();
        tendernessMark2 = new javax.swing.JRadioButton();
        tendernessMark3 = new javax.swing.JRadioButton();
        tendernessMark4 = new javax.swing.JRadioButton();
        tendernessMark5 = new javax.swing.JRadioButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tendernessNotes = new javax.swing.JTextArea();
        nostalgiaPane = new javax.swing.JPanel();
        nostalgiaTitle = new javax.swing.JLabel();
        nostalgiaDescription = new javax.swing.JLabel();
        nostalgiaMarksPanel = new javax.swing.JPanel();
        nostalgiaMark1 = new javax.swing.JRadioButton();
        nostalgiaMark2 = new javax.swing.JRadioButton();
        nostalgiaMark3 = new javax.swing.JRadioButton();
        nostalgiaMark4 = new javax.swing.JRadioButton();
        nostalgiaMark5 = new javax.swing.JRadioButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        nostalgiaNotes = new javax.swing.JTextArea();
        calmnessPane = new javax.swing.JPanel();
        calmnessTitle = new javax.swing.JLabel();
        calmnessDescription = new javax.swing.JLabel();
        calmnessMarkPanel = new javax.swing.JPanel();
        calmnessMark1 = new javax.swing.JRadioButton();
        calmnessMark2 = new javax.swing.JRadioButton();
        calmnessMark3 = new javax.swing.JRadioButton();
        calmnessMark4 = new javax.swing.JRadioButton();
        calmnessMark5 = new javax.swing.JRadioButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        calmnessNotes = new javax.swing.JTextArea();
        powerPane = new javax.swing.JPanel();
        powerTitle = new javax.swing.JLabel();
        powerDescription = new javax.swing.JLabel();
        powerMarksPanel = new javax.swing.JPanel();
        powerMark1 = new javax.swing.JRadioButton();
        powerMark2 = new javax.swing.JRadioButton();
        powerMark3 = new javax.swing.JRadioButton();
        powerMark4 = new javax.swing.JRadioButton();
        powerMark5 = new javax.swing.JRadioButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        powerNotes = new javax.swing.JTextArea();
        joyPane = new javax.swing.JPanel();
        joyTitle = new javax.swing.JLabel();
        joyDescription = new javax.swing.JLabel();
        joyMarksPanel = new javax.swing.JPanel();
        joyMark1 = new javax.swing.JRadioButton();
        joyMark2 = new javax.swing.JRadioButton();
        joyMark3 = new javax.swing.JRadioButton();
        joyMark4 = new javax.swing.JRadioButton();
        joyMark5 = new javax.swing.JRadioButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        joyNotes = new javax.swing.JTextArea();
        tensionPane = new javax.swing.JPanel();
        tensionTitle = new javax.swing.JLabel();
        tensionDescription = new javax.swing.JLabel();
        tensionMarksPanel = new javax.swing.JPanel();
        tensionMark1 = new javax.swing.JRadioButton();
        tensionMark2 = new javax.swing.JRadioButton();
        tensionMark3 = new javax.swing.JRadioButton();
        tensionMark4 = new javax.swing.JRadioButton();
        tensionMark5 = new javax.swing.JRadioButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        tensionNotes = new javax.swing.JTextArea();
        sadnessPane = new javax.swing.JPanel();
        sadnessTitle = new javax.swing.JLabel();
        sadnessDescription = new javax.swing.JLabel();
        sadnessMarksPanes = new javax.swing.JPanel();
        sadnessMark1 = new javax.swing.JRadioButton();
        sadnessMark2 = new javax.swing.JRadioButton();
        sadnessMark3 = new javax.swing.JRadioButton();
        sadnessMark4 = new javax.swing.JRadioButton();
        sadnessMark5 = new javax.swing.JRadioButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        sadnessNotes = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        CompleteOperation = new javax.swing.JButton();
        AbortOperation = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1020, 3662));
        setLayout(new java.awt.BorderLayout());

        innerPanel.setPreferredSize(new java.awt.Dimension(998, 3600));
        innerPanel.setLayout(new java.awt.GridLayout(10, 1));

        amazementPane.setLayout(new java.awt.BorderLayout());

        GeneralDescriptionPane.setPreferredSize(new java.awt.Dimension(996, 50));
        GeneralDescriptionPane.setLayout(new java.awt.BorderLayout());

        songDataLabel.setBackground(new java.awt.Color(255, 255, 255));
        songDataLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        songDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songDataLabel.setText(EmotionalSongs.dialoghi.titleCapitalizedWithColon() + songUnderVotation.getTitle() + " - " +
            EmotionalSongs.dialoghi.authorCapitalizedWithColon() + songUnderVotation.getAuthor() + " - " +
            EmotionalSongs.dialoghi.yearOfPublication() + songUnderVotation.getYear());
        songDataLabel.setOpaque(true);
        GeneralDescriptionPane.add(songDataLabel, java.awt.BorderLayout.CENTER);

        amazementPane.add(GeneralDescriptionPane, java.awt.BorderLayout.PAGE_START);

        mainAmazementEmotionPane.setBackground(new java.awt.Color(255, 255, 255));
        mainAmazementEmotionPane.setLayout(new java.awt.GridBagLayout());

        amazementTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        amazementTitle.setText(emotionalsongs.basic_structures.Emotions.AMAZEMENT.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        mainAmazementEmotionPane.add(amazementTitle, gridBagConstraints);

        amazementDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        amazementDescription.setText(emotionalsongs.basic_structures.Emotions.AMAZEMENT.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        mainAmazementEmotionPane.add(amazementDescription, gridBagConstraints);

        amazementMarksPanel.setBackground(new java.awt.Color(255, 255, 255));
        amazementMarksPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        amazementMarksPanel.setLayout(new java.awt.GridLayout(1, 5));

        amazementMark1.setText("1");
        amazementMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amazementMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazementMark1ActionPerformed(evt);
            }
        });
        amazementMarksPanel.add(amazementMark1);

        amazementMark2.setText("2");
        amazementMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amazementMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazementMark2ActionPerformed(evt);
            }
        });
        amazementMarksPanel.add(amazementMark2);

        amazementMark3.setText("3");
        amazementMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amazementMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazementMark3ActionPerformed(evt);
            }
        });
        amazementMarksPanel.add(amazementMark3);

        amazementMark4.setText("4");
        amazementMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amazementMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazementMark4ActionPerformed(evt);
            }
        });
        amazementMarksPanel.add(amazementMark4);

        amazementMark5.setText("5");
        amazementMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amazementMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazementMark5ActionPerformed(evt);
            }
        });
        amazementMarksPanel.add(amazementMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        mainAmazementEmotionPane.add(amazementMarksPanel, gridBagConstraints);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 150));

        amazementNotes.setColumns(20);
        amazementNotes.setRows(5);
        amazementNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        amazementNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane2.setViewportView(amazementNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        mainAmazementEmotionPane.add(jScrollPane2, gridBagConstraints);

        amazementPane.add(mainAmazementEmotionPane, java.awt.BorderLayout.CENTER);

        innerPanel.add(amazementPane);

        solemnityPane.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout solemnityPaneLayout = new java.awt.GridBagLayout();
        solemnityPaneLayout.columnWidths = new int[] {0, 15, 0};
        solemnityPaneLayout.rowHeights = new int[] {0, 15, 0, 15, 0, 15, 0};
        solemnityPane.setLayout(solemnityPaneLayout);

        solemnityTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        solemnityTitle.setText(emotionalsongs.basic_structures.Emotions.SOLEMNITY.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        solemnityPane.add(solemnityTitle, gridBagConstraints);

        solemnityDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        solemnityDescription.setText(emotionalsongs.basic_structures.Emotions.SOLEMNITY.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        solemnityPane.add(solemnityDescription, gridBagConstraints);

        solemnityMarksPane.setBackground(new java.awt.Color(255, 255, 255));
        solemnityMarksPane.setPreferredSize(new java.awt.Dimension(500, 50));
        solemnityMarksPane.setLayout(new java.awt.GridLayout(1, 5));

        solemnityMark1.setText("1");
        solemnityMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solemnityMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solemnityMark1ActionPerformed(evt);
            }
        });
        solemnityMarksPane.add(solemnityMark1);

        solemnityMark2.setText("2");
        solemnityMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solemnityMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solemnityMark2ActionPerformed(evt);
            }
        });
        solemnityMarksPane.add(solemnityMark2);

        solemnityMark3.setText("3");
        solemnityMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solemnityMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solemnityMark3ActionPerformed(evt);
            }
        });
        solemnityMarksPane.add(solemnityMark3);

        solemnityMark4.setText("4");
        solemnityMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solemnityMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solemnityMark4ActionPerformed(evt);
            }
        });
        solemnityMarksPane.add(solemnityMark4);

        solemnityMark5.setText("5");
        solemnityMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solemnityMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solemnityMark5ActionPerformed(evt);
            }
        });
        solemnityMarksPane.add(solemnityMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        solemnityPane.add(solemnityMarksPane, gridBagConstraints);

        jScrollPane11.setPreferredSize(new java.awt.Dimension(800, 150));

        solemnityNotes.setColumns(20);
        solemnityNotes.setRows(5);
        solemnityNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        solemnityNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane11.setViewportView(solemnityNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        solemnityPane.add(jScrollPane11, gridBagConstraints);

        innerPanel.add(solemnityPane);

        tendernessPane.setBackground(java.awt.Color.white);
        tendernessPane.setLayout(new java.awt.GridBagLayout());

        tendernessTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        tendernessTitle.setText(emotionalsongs.basic_structures.Emotions.TENDERNESS.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        tendernessPane.add(tendernessTitle, gridBagConstraints);

        tendernessDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tendernessDescription.setText(emotionalsongs.basic_structures.Emotions.TENDERNESS.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        tendernessPane.add(tendernessDescription, gridBagConstraints);

        tendernessMarksPanel.setBackground(new java.awt.Color(255, 255, 255));
        tendernessMarksPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        tendernessMarksPanel.setLayout(new java.awt.GridLayout(1, 5));

        tendernessMark1.setText("1");
        tendernessMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendernessMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendernessMark1ActionPerformed(evt);
            }
        });
        tendernessMarksPanel.add(tendernessMark1);

        tendernessMark2.setText("2");
        tendernessMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendernessMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendernessMark2ActionPerformed(evt);
            }
        });
        tendernessMarksPanel.add(tendernessMark2);

        tendernessMark3.setText("3");
        tendernessMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendernessMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendernessMark3ActionPerformed(evt);
            }
        });
        tendernessMarksPanel.add(tendernessMark3);

        tendernessMark4.setText("4");
        tendernessMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendernessMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendernessMark4ActionPerformed(evt);
            }
        });
        tendernessMarksPanel.add(tendernessMark4);

        tendernessMark5.setText("5");
        tendernessMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tendernessMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendernessMark5ActionPerformed(evt);
            }
        });
        tendernessMarksPanel.add(tendernessMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        tendernessPane.add(tendernessMarksPanel, gridBagConstraints);

        jScrollPane12.setPreferredSize(new java.awt.Dimension(800, 150));

        tendernessNotes.setColumns(20);
        tendernessNotes.setRows(5);
        tendernessNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        tendernessNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane12.setViewportView(tendernessNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        tendernessPane.add(jScrollPane12, gridBagConstraints);

        innerPanel.add(tendernessPane);

        nostalgiaPane.setBackground(java.awt.Color.white);
        nostalgiaPane.setLayout(new java.awt.GridBagLayout());

        nostalgiaTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        nostalgiaTitle.setText(emotionalsongs.basic_structures.Emotions.NOSTALGIA.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        nostalgiaPane.add(nostalgiaTitle, gridBagConstraints);

        nostalgiaDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        nostalgiaDescription.setText(emotionalsongs.basic_structures.Emotions.NOSTALGIA.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        nostalgiaPane.add(nostalgiaDescription, gridBagConstraints);

        nostalgiaMarksPanel.setBackground(new java.awt.Color(255, 255, 255));
        nostalgiaMarksPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        nostalgiaMarksPanel.setLayout(new java.awt.GridLayout(1, 5));

        nostalgiaMark1.setText("1");
        nostalgiaMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nostalgiaMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nostalgiaMark1ActionPerformed(evt);
            }
        });
        nostalgiaMarksPanel.add(nostalgiaMark1);

        nostalgiaMark2.setText("2");
        nostalgiaMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nostalgiaMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nostalgiaMark2ActionPerformed(evt);
            }
        });
        nostalgiaMarksPanel.add(nostalgiaMark2);

        nostalgiaMark3.setText("3");
        nostalgiaMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nostalgiaMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nostalgiaMark3ActionPerformed(evt);
            }
        });
        nostalgiaMarksPanel.add(nostalgiaMark3);

        nostalgiaMark4.setText("4");
        nostalgiaMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nostalgiaMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nostalgiaMark4ActionPerformed(evt);
            }
        });
        nostalgiaMarksPanel.add(nostalgiaMark4);

        nostalgiaMark5.setText("5");
        nostalgiaMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nostalgiaMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nostalgiaMark5ActionPerformed(evt);
            }
        });
        nostalgiaMarksPanel.add(nostalgiaMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        nostalgiaPane.add(nostalgiaMarksPanel, gridBagConstraints);

        jScrollPane13.setPreferredSize(new java.awt.Dimension(800, 150));

        nostalgiaNotes.setColumns(20);
        nostalgiaNotes.setRows(5);
        nostalgiaNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        nostalgiaNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane13.setViewportView(nostalgiaNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        nostalgiaPane.add(jScrollPane13, gridBagConstraints);

        innerPanel.add(nostalgiaPane);

        calmnessPane.setBackground(java.awt.Color.white);
        calmnessPane.setLayout(new java.awt.GridBagLayout());

        calmnessTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        calmnessTitle.setText(emotionalsongs.basic_structures.Emotions.CALMNESS.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        calmnessPane.add(calmnessTitle, gridBagConstraints);

        calmnessDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        calmnessDescription.setText(emotionalsongs.basic_structures.Emotions.CALMNESS.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        calmnessPane.add(calmnessDescription, gridBagConstraints);

        calmnessMarkPanel.setBackground(new java.awt.Color(255, 255, 255));
        calmnessMarkPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        calmnessMarkPanel.setLayout(new java.awt.GridLayout(1, 5));

        calmnessMark1.setText("1");
        calmnessMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calmnessMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calmnessMark1ActionPerformed(evt);
            }
        });
        calmnessMarkPanel.add(calmnessMark1);

        calmnessMark2.setText("2");
        calmnessMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calmnessMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calmnessMark2ActionPerformed(evt);
            }
        });
        calmnessMarkPanel.add(calmnessMark2);

        calmnessMark3.setText("3");
        calmnessMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calmnessMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calmnessMark3ActionPerformed(evt);
            }
        });
        calmnessMarkPanel.add(calmnessMark3);

        calmnessMark4.setText("4");
        calmnessMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calmnessMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calmnessMark4ActionPerformed(evt);
            }
        });
        calmnessMarkPanel.add(calmnessMark4);

        calmnessMark5.setText("5");
        calmnessMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calmnessMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calmnessMark5ActionPerformed(evt);
            }
        });
        calmnessMarkPanel.add(calmnessMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        calmnessPane.add(calmnessMarkPanel, gridBagConstraints);

        jScrollPane14.setPreferredSize(new java.awt.Dimension(800, 150));

        calmnessNotes.setColumns(20);
        calmnessNotes.setRows(5);
        calmnessNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        calmnessNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane14.setViewportView(calmnessNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        calmnessPane.add(jScrollPane14, gridBagConstraints);

        innerPanel.add(calmnessPane);

        powerPane.setBackground(java.awt.Color.white);
        powerPane.setLayout(new java.awt.GridBagLayout());

        powerTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        powerTitle.setText(emotionalsongs.basic_structures.Emotions.POWER.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        powerPane.add(powerTitle, gridBagConstraints);

        powerDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        powerDescription.setText(emotionalsongs.basic_structures.Emotions.POWER.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        powerPane.add(powerDescription, gridBagConstraints);

        powerMarksPanel.setBackground(new java.awt.Color(255, 255, 255));
        powerMarksPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        powerMarksPanel.setLayout(new java.awt.GridLayout(1, 5));

        powerMark1.setText("1");
        powerMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerMark1ActionPerformed(evt);
            }
        });
        powerMarksPanel.add(powerMark1);

        powerMark2.setText("2");
        powerMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerMark2ActionPerformed(evt);
            }
        });
        powerMarksPanel.add(powerMark2);

        powerMark3.setText("3");
        powerMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerMark3ActionPerformed(evt);
            }
        });
        powerMarksPanel.add(powerMark3);

        powerMark4.setText("4");
        powerMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerMark4ActionPerformed(evt);
            }
        });
        powerMarksPanel.add(powerMark4);

        powerMark5.setText("5");
        powerMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        powerMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerMark5ActionPerformed(evt);
            }
        });
        powerMarksPanel.add(powerMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        powerPane.add(powerMarksPanel, gridBagConstraints);

        jScrollPane15.setPreferredSize(new java.awt.Dimension(800, 150));

        powerNotes.setColumns(20);
        powerNotes.setRows(5);
        powerNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        powerNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane15.setViewportView(powerNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        powerPane.add(jScrollPane15, gridBagConstraints);

        innerPanel.add(powerPane);

        joyPane.setBackground(java.awt.Color.white);
        joyPane.setLayout(new java.awt.GridBagLayout());

        joyTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        joyTitle.setText(emotionalsongs.basic_structures.Emotions.JOY.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        joyPane.add(joyTitle, gridBagConstraints);

        joyDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        joyDescription.setText(emotionalsongs.basic_structures.Emotions.JOY.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        joyPane.add(joyDescription, gridBagConstraints);

        joyMarksPanel.setBackground(new java.awt.Color(255, 255, 255));
        joyMarksPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        joyMarksPanel.setLayout(new java.awt.GridLayout(1, 5));

        joyMark1.setText("1");
        joyMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joyMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joyMark1ActionPerformed(evt);
            }
        });
        joyMarksPanel.add(joyMark1);

        joyMark2.setText("2");
        joyMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joyMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joyMark2ActionPerformed(evt);
            }
        });
        joyMarksPanel.add(joyMark2);

        joyMark3.setText("3");
        joyMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joyMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joyMark3ActionPerformed(evt);
            }
        });
        joyMarksPanel.add(joyMark3);

        joyMark4.setText("4");
        joyMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joyMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joyMark4ActionPerformed(evt);
            }
        });
        joyMarksPanel.add(joyMark4);

        joyMark5.setText("5");
        joyMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joyMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joyMark5ActionPerformed(evt);
            }
        });
        joyMarksPanel.add(joyMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        joyPane.add(joyMarksPanel, gridBagConstraints);

        jScrollPane16.setPreferredSize(new java.awt.Dimension(800, 150));

        joyNotes.setColumns(20);
        joyNotes.setRows(5);
        joyNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        joyNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane16.setViewportView(joyNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        joyPane.add(jScrollPane16, gridBagConstraints);

        innerPanel.add(joyPane);

        tensionPane.setBackground(java.awt.Color.white);
        tensionPane.setLayout(new java.awt.GridBagLayout());

        tensionTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        tensionTitle.setText(emotionalsongs.basic_structures.Emotions.TENSION.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        tensionPane.add(tensionTitle, gridBagConstraints);

        tensionDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tensionDescription.setText(emotionalsongs.basic_structures.Emotions.TENSION.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        tensionPane.add(tensionDescription, gridBagConstraints);

        tensionMarksPanel.setBackground(new java.awt.Color(255, 255, 255));
        tensionMarksPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        tensionMarksPanel.setLayout(new java.awt.GridLayout(1, 5));

        tensionMark1.setText("1");
        tensionMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tensionMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensionMark1ActionPerformed(evt);
            }
        });
        tensionMarksPanel.add(tensionMark1);

        tensionMark2.setText("2");
        tensionMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tensionMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensionMark2ActionPerformed(evt);
            }
        });
        tensionMarksPanel.add(tensionMark2);

        tensionMark3.setText("3");
        tensionMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tensionMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensionMark3ActionPerformed(evt);
            }
        });
        tensionMarksPanel.add(tensionMark3);

        tensionMark4.setText("4");
        tensionMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tensionMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensionMark4ActionPerformed(evt);
            }
        });
        tensionMarksPanel.add(tensionMark4);

        tensionMark5.setText("5");
        tensionMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tensionMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensionMark5ActionPerformed(evt);
            }
        });
        tensionMarksPanel.add(tensionMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        tensionPane.add(tensionMarksPanel, gridBagConstraints);

        jScrollPane17.setPreferredSize(new java.awt.Dimension(800, 150));

        tensionNotes.setColumns(20);
        tensionNotes.setRows(5);
        tensionNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        tensionNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane17.setViewportView(tensionNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        tensionPane.add(jScrollPane17, gridBagConstraints);

        innerPanel.add(tensionPane);

        sadnessPane.setBackground(java.awt.Color.white);
        sadnessPane.setLayout(new java.awt.GridBagLayout());

        sadnessTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        sadnessTitle.setText(emotionalsongs.basic_structures.Emotions.SADNESS.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        sadnessPane.add(sadnessTitle, gridBagConstraints);

        sadnessDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        sadnessDescription.setText(emotionalsongs.basic_structures.Emotions.SADNESS.getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        sadnessPane.add(sadnessDescription, gridBagConstraints);

        sadnessMarksPanes.setBackground(new java.awt.Color(255, 255, 255));
        sadnessMarksPanes.setPreferredSize(new java.awt.Dimension(500, 50));
        sadnessMarksPanes.setLayout(new java.awt.GridLayout(1, 5));

        sadnessMark1.setText("1");
        sadnessMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sadnessMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadnessMark1ActionPerformed(evt);
            }
        });
        sadnessMarksPanes.add(sadnessMark1);

        sadnessMark2.setText("2");
        sadnessMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sadnessMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadnessMark2ActionPerformed(evt);
            }
        });
        sadnessMarksPanes.add(sadnessMark2);

        sadnessMark3.setText("3");
        sadnessMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sadnessMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadnessMark3ActionPerformed(evt);
            }
        });
        sadnessMarksPanes.add(sadnessMark3);

        sadnessMark4.setText("4");
        sadnessMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sadnessMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadnessMark4ActionPerformed(evt);
            }
        });
        sadnessMarksPanes.add(sadnessMark4);

        sadnessMark5.setText("5");
        sadnessMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sadnessMark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadnessMark5ActionPerformed(evt);
            }
        });
        sadnessMarksPanes.add(sadnessMark5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        sadnessPane.add(sadnessMarksPanes, gridBagConstraints);

        jScrollPane18.setPreferredSize(new java.awt.Dimension(800, 150));

        sadnessNotes.setColumns(20);
        sadnessNotes.setRows(5);
        sadnessNotes.setText(emotionalsongs.EmotionalSongs.dialoghi.songsJudgeCommentRequest());
        sadnessNotes.setPreferredSize(new java.awt.Dimension(800, 150));
        jScrollPane18.setViewportView(sadnessNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        sadnessPane.add(jScrollPane18, gridBagConstraints);

        innerPanel.add(sadnessPane);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setPreferredSize(new java.awt.Dimension(150, 205));
        buttonPanel.setLayout(new java.awt.GridLayout(5, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 85));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0, 15, 0};
        jPanel1.setLayout(jPanel1Layout);

        CompleteOperation.setBackground(new java.awt.Color(153, 204, 0));
        CompleteOperation.setForeground(new java.awt.Color(255, 255, 255));
        CompleteOperation.setText(EmotionalSongs.dialoghi.vote());
        CompleteOperation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CompleteOperation.setOpaque(true);
        CompleteOperation.setPreferredSize(new java.awt.Dimension(150, 30));
        CompleteOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteOperationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(CompleteOperation, gridBagConstraints);

        AbortOperation.setBackground(new java.awt.Color(255, 0, 51));
        AbortOperation.setForeground(new java.awt.Color(255, 255, 255));
        AbortOperation.setText(EmotionalSongs.dialoghi.abort());
        AbortOperation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AbortOperation.setOpaque(true);
        AbortOperation.setPreferredSize(new java.awt.Dimension(100, 25));
        AbortOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbortOperationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(AbortOperation, gridBagConstraints);

        buttonPanel.add(jPanel1);

        innerPanel.add(buttonPanel);

        jScrollPane1.setViewportView(innerPanel);

        add(jScrollPane1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents
    //solemnityZone
    private void solemnityMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solemnityMark1ActionPerformed
        marks[1] = 1;
        solemnityMark2.setSelected(false);
        solemnityMark3.setSelected(false);
        solemnityMark4.setSelected(false);
        solemnityMark5.setSelected(false);
    }//GEN-LAST:event_solemnityMark1ActionPerformed

    private void solemnityMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solemnityMark2ActionPerformed
        marks[1] = 2;
        solemnityMark1.setSelected(false);
        solemnityMark3.setSelected(false);
        solemnityMark4.setSelected(false);
        solemnityMark5.setSelected(false);
    }//GEN-LAST:event_solemnityMark2ActionPerformed

    private void solemnityMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solemnityMark3ActionPerformed
        marks[1] = 3;
        solemnityMark2.setSelected(false);
        solemnityMark1.setSelected(false);
        solemnityMark4.setSelected(false);
        solemnityMark5.setSelected(false);
    }//GEN-LAST:event_solemnityMark3ActionPerformed

    private void solemnityMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solemnityMark4ActionPerformed
        marks[1] = 4;
        solemnityMark2.setSelected(false);
        solemnityMark3.setSelected(false);
        solemnityMark1.setSelected(false);
        solemnityMark5.setSelected(false);
    }//GEN-LAST:event_solemnityMark4ActionPerformed

    private void solemnityMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solemnityMark5ActionPerformed
        marks[1] = 5;
        solemnityMark2.setSelected(false);
        solemnityMark3.setSelected(false);
        solemnityMark4.setSelected(false);
        solemnityMark1.setSelected(false);
    }//GEN-LAST:event_solemnityMark5ActionPerformed
    //tenderness Zone
    private void tendernessMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendernessMark1ActionPerformed
        marks[2] = 1;
        tendernessMark2.setSelected(false);
        tendernessMark3.setSelected(false);
        tendernessMark4.setSelected(false);
        tendernessMark5.setSelected(false);
    }//GEN-LAST:event_tendernessMark1ActionPerformed

    private void tendernessMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendernessMark2ActionPerformed
        marks[2] = 2;
        tendernessMark1.setSelected(false);
        tendernessMark3.setSelected(false);
        tendernessMark4.setSelected(false);
        tendernessMark5.setSelected(false);
    }//GEN-LAST:event_tendernessMark2ActionPerformed

    private void tendernessMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendernessMark3ActionPerformed
        marks[2] = 3;
        tendernessMark2.setSelected(false);
        tendernessMark1.setSelected(false);
        tendernessMark4.setSelected(false);
        tendernessMark5.setSelected(false);
    }//GEN-LAST:event_tendernessMark3ActionPerformed

    private void tendernessMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendernessMark4ActionPerformed
        marks[2] = 4;
        tendernessMark1.setSelected(false);
        tendernessMark2.setSelected(false);
        tendernessMark3.setSelected(false);
        tendernessMark5.setSelected(false);
    }//GEN-LAST:event_tendernessMark4ActionPerformed

    private void tendernessMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendernessMark5ActionPerformed
        marks[2] = 5;
        tendernessMark1.setSelected(false);
        tendernessMark2.setSelected(false);
        tendernessMark3.setSelected(false);
        tendernessMark4.setSelected(false);
    }//GEN-LAST:event_tendernessMark5ActionPerformed
    //nostalgia Zone
    private void nostalgiaMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nostalgiaMark1ActionPerformed
        marks[3] = 1;
        nostalgiaMark2.setSelected(false);
        nostalgiaMark3.setSelected(false);
        nostalgiaMark4.setSelected(false);
        nostalgiaMark5.setSelected(false);
    }//GEN-LAST:event_nostalgiaMark1ActionPerformed

    private void nostalgiaMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nostalgiaMark2ActionPerformed
        marks[3] = 2;
        nostalgiaMark1.setSelected(false);
        nostalgiaMark3.setSelected(false);
        nostalgiaMark4.setSelected(false);
        nostalgiaMark5.setSelected(false);
    }//GEN-LAST:event_nostalgiaMark2ActionPerformed

    private void nostalgiaMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nostalgiaMark3ActionPerformed
        marks[3] = 3;
        nostalgiaMark1.setSelected(false);
        nostalgiaMark2.setSelected(false);
        nostalgiaMark4.setSelected(false);
        nostalgiaMark5.setSelected(false);
    }//GEN-LAST:event_nostalgiaMark3ActionPerformed

    private void nostalgiaMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nostalgiaMark4ActionPerformed
        marks[3] = 4;
        nostalgiaMark1.setSelected(false);
        nostalgiaMark2.setSelected(false);
        nostalgiaMark3.setSelected(false);
        nostalgiaMark5.setSelected(false);
    }//GEN-LAST:event_nostalgiaMark4ActionPerformed

    private void nostalgiaMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nostalgiaMark5ActionPerformed
        marks[3] = 5;
        nostalgiaMark1.setSelected(false);
        nostalgiaMark2.setSelected(false);
        nostalgiaMark3.setSelected(false);
        nostalgiaMark4.setSelected(false);
    }//GEN-LAST:event_nostalgiaMark5ActionPerformed
    //calmness Zone
    private void calmnessMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calmnessMark1ActionPerformed
        marks[4] = 1;
        calmnessMark2.setSelected(false);
        calmnessMark3.setSelected(false);
        calmnessMark4.setSelected(false);
        calmnessMark5.setSelected(false);
    }//GEN-LAST:event_calmnessMark1ActionPerformed

    private void calmnessMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calmnessMark2ActionPerformed
        marks[4] = 2;
        calmnessMark1.setSelected(false);
        calmnessMark3.setSelected(false);
        calmnessMark4.setSelected(false);
        calmnessMark5.setSelected(false);
    }//GEN-LAST:event_calmnessMark2ActionPerformed

    private void calmnessMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calmnessMark3ActionPerformed
        marks[4] = 3;
        calmnessMark1.setSelected(false);
        calmnessMark2.setSelected(false);
        calmnessMark4.setSelected(false);
        calmnessMark5.setSelected(false);
    }//GEN-LAST:event_calmnessMark3ActionPerformed

    private void calmnessMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calmnessMark4ActionPerformed
        marks[4] = 4;
        calmnessMark2.setSelected(false);
        calmnessMark3.setSelected(false);
        calmnessMark1.setSelected(false);
        calmnessMark5.setSelected(false);
    }//GEN-LAST:event_calmnessMark4ActionPerformed

    private void calmnessMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calmnessMark5ActionPerformed
        marks[4] = 5;
        calmnessMark2.setSelected(false);
        calmnessMark3.setSelected(false);
        calmnessMark4.setSelected(false);
        calmnessMark1.setSelected(false);
    }//GEN-LAST:event_calmnessMark5ActionPerformed
    //power zone
    private void powerMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerMark1ActionPerformed
        marks[5] = 1;
        powerMark2.setSelected(false);
        powerMark3.setSelected(false);
        powerMark4.setSelected(false);
        powerMark5.setSelected(false);
    }//GEN-LAST:event_powerMark1ActionPerformed

    private void powerMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerMark2ActionPerformed
        marks[5] = 2;
        powerMark1.setSelected(false);
        powerMark3.setSelected(false);
        powerMark4.setSelected(false);
        powerMark5.setSelected(false);
    }//GEN-LAST:event_powerMark2ActionPerformed

    private void powerMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerMark3ActionPerformed
        marks[5] = 3;
        powerMark2.setSelected(false);
        powerMark1.setSelected(false);
        powerMark4.setSelected(false);
        powerMark5.setSelected(false);
    }//GEN-LAST:event_powerMark3ActionPerformed

    private void powerMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerMark4ActionPerformed
        marks[5] = 4;
        powerMark2.setSelected(false);
        powerMark3.setSelected(false);
        powerMark1.setSelected(false);
        powerMark5.setSelected(false);
    }//GEN-LAST:event_powerMark4ActionPerformed

    private void powerMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerMark5ActionPerformed
        marks[5] = 5;
        powerMark2.setSelected(false);
        powerMark3.setSelected(false);
        powerMark4.setSelected(false);
        powerMark1.setSelected(false);
    }//GEN-LAST:event_powerMark5ActionPerformed
    //joy zone
    private void joyMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joyMark1ActionPerformed
        marks[6] = 1;
        joyMark2.setSelected(false);
        joyMark3.setSelected(false);
        joyMark4.setSelected(false);
        joyMark5.setSelected(false);
    }//GEN-LAST:event_joyMark1ActionPerformed

    private void joyMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joyMark2ActionPerformed
        marks[6] = 2;
        joyMark1.setSelected(false);
        joyMark3.setSelected(false);
        joyMark4.setSelected(false);
        joyMark5.setSelected(false);
    }//GEN-LAST:event_joyMark2ActionPerformed

    private void joyMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joyMark3ActionPerformed
        marks[6] = 3;
        joyMark2.setSelected(false);
        joyMark1.setSelected(false);
        joyMark4.setSelected(false);
        joyMark5.setSelected(false);
    }//GEN-LAST:event_joyMark3ActionPerformed

    private void joyMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joyMark4ActionPerformed
        marks[6] = 4;
        joyMark2.setSelected(false);
        joyMark3.setSelected(false);
        joyMark1.setSelected(false);
        joyMark5.setSelected(false);
    }//GEN-LAST:event_joyMark4ActionPerformed

    private void joyMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joyMark5ActionPerformed
        marks[6] = 5;
        joyMark2.setSelected(false);
        joyMark3.setSelected(false);
        joyMark4.setSelected(false);
        joyMark1.setSelected(false);
    }//GEN-LAST:event_joyMark5ActionPerformed
    //tension Zone
    private void tensionMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensionMark1ActionPerformed
        marks[7] = 1;
        tensionMark2.setSelected(false);
        tensionMark3.setSelected(false);
        tensionMark4.setSelected(false);
        tensionMark5.setSelected(false);
    }//GEN-LAST:event_tensionMark1ActionPerformed

    private void tensionMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensionMark2ActionPerformed
        marks[7] = 2;
        tensionMark1.setSelected(false);
        tensionMark3.setSelected(false);
        tensionMark4.setSelected(false);
        tensionMark5.setSelected(false);
    }//GEN-LAST:event_tensionMark2ActionPerformed

    private void tensionMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensionMark3ActionPerformed
        marks[7] = 3;
        tensionMark2.setSelected(false);
        tensionMark1.setSelected(false);
        tensionMark4.setSelected(false);
        tensionMark5.setSelected(false);
    }//GEN-LAST:event_tensionMark3ActionPerformed

    private void tensionMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensionMark4ActionPerformed
        marks[7] = 4;
        tensionMark2.setSelected(false);
        tensionMark3.setSelected(false);
        tensionMark1.setSelected(false);
        tensionMark5.setSelected(false);
    }//GEN-LAST:event_tensionMark4ActionPerformed

    private void tensionMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensionMark5ActionPerformed
        marks[7] = 5;
        tensionMark2.setSelected(false);
        tensionMark3.setSelected(false);
        tensionMark4.setSelected(false);
        tensionMark1.setSelected(false);
    }//GEN-LAST:event_tensionMark5ActionPerformed
    //sadness zone
    private void sadnessMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadnessMark1ActionPerformed
        marks[8] = 1;
        sadnessMark2.setSelected(false);
        sadnessMark3.setSelected(false);
        sadnessMark4.setSelected(false);
        sadnessMark5.setSelected(false);
    }//GEN-LAST:event_sadnessMark1ActionPerformed

    private void sadnessMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadnessMark2ActionPerformed
        marks[8] = 2;
        sadnessMark1.setSelected(false);
        sadnessMark3.setSelected(false);
        sadnessMark4.setSelected(false);
        sadnessMark5.setSelected(false);
    }//GEN-LAST:event_sadnessMark2ActionPerformed

    private void sadnessMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadnessMark3ActionPerformed
        marks[8] = 3;
        sadnessMark2.setSelected(false);
        sadnessMark1.setSelected(false);
        sadnessMark4.setSelected(false);
        sadnessMark5.setSelected(false);
    }//GEN-LAST:event_sadnessMark3ActionPerformed

    private void amazementMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amazementMark5ActionPerformed
        marks[0] = 5;
        amazementMark2.setSelected(false);
        amazementMark3.setSelected(false);
        amazementMark4.setSelected(false);
        amazementMark1.setSelected(false);
    }//GEN-LAST:event_amazementMark5ActionPerformed

    private void amazementMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amazementMark4ActionPerformed
        marks[0] = 4;
        amazementMark2.setSelected(false);
        amazementMark3.setSelected(false);
        amazementMark1.setSelected(false);
        amazementMark5.setSelected(false);
    }//GEN-LAST:event_amazementMark4ActionPerformed

    private void amazementMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amazementMark3ActionPerformed
        marks[0] = 3;
        amazementMark2.setSelected(false);
        amazementMark1.setSelected(false);
        amazementMark4.setSelected(false);
        amazementMark5.setSelected(false);
    }//GEN-LAST:event_amazementMark3ActionPerformed

    private void amazementMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amazementMark2ActionPerformed
        marks[0] = 2;
        amazementMark1.setSelected(false);
        amazementMark3.setSelected(false);
        amazementMark4.setSelected(false);
        amazementMark5.setSelected(false);
    }//GEN-LAST:event_amazementMark2ActionPerformed

    //amazementZone
    private void amazementMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amazementMark1ActionPerformed
        marks[0] = 1;
        amazementMark2.setSelected(false);
        amazementMark3.setSelected(false);
        amazementMark4.setSelected(false);
        amazementMark5.setSelected(false);
    }//GEN-LAST:event_amazementMark1ActionPerformed

    private void sadnessMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadnessMark4ActionPerformed
        marks[8] = 4;
        sadnessMark2.setSelected(false);
        sadnessMark3.setSelected(false);
        sadnessMark1.setSelected(false);
        sadnessMark5.setSelected(false);
    }//GEN-LAST:event_sadnessMark4ActionPerformed

    private void sadnessMark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadnessMark5ActionPerformed
        marks[8] = 5;
        sadnessMark2.setSelected(false);
        sadnessMark3.setSelected(false);
        sadnessMark4.setSelected(false);
        sadnessMark1.setSelected(false);
    }//GEN-LAST:event_sadnessMark5ActionPerformed

    private void CompleteOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteOperationActionPerformed
        if(allEmotionsVoted()) {
            notes[0] = amazementNotes.getText();
            notes[1] = solemnityNotes.getText();
            notes[2] = tendernessNotes.getText();
            notes[3] = nostalgiaNotes.getText();
            notes[4] = calmnessNotes.getText();
            notes[5] = powerNotes.getText();
            notes[6] = joyNotes.getText();
            notes[7] = tensionNotes.getText();
            notes[8] = sadnessNotes.getText();

            for(int i=0;i<notes.length;i++) {
                if(notes[i].length()<256)
                    notes[i] = formatAndCleanString(notes[i]);
                else {
                    new PopUpAllert(EmotionalSongs.dialoghi.maxStringLong255()).setVisible(true);
                    return;
                }
            }

            DataBaseJudgements dataBaseRecords = DataBaseJudgements.getInstance();
            dataBaseRecords.inserisciEmozioneBrano(new EmotionalJudgement(
                songToVoteTag,
                loggedUserId,
                marks[0],notes[0],//amazement
                marks[1],notes[1],//solemnity
                marks[2],notes[2],//tenderness
                marks[3],notes[3],//nostalgia
                marks[4],notes[4],//calmness
                marks[5],notes[5],//power
                marks[6],notes[6],//joy
                marks[7],notes[7],//tension
                marks[8],notes[8]//sadness
            ));
            callerComponent.setVoteButton(false);
            callerComponent.revalidate();
            callerComponent.repaint();
            SwingUtilities.getWindowAncestor(this).dispose();
            
        }

    }//GEN-LAST:event_CompleteOperationActionPerformed

    private void AbortOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbortOperationActionPerformed
        container.dispose();
    }//GEN-LAST:event_AbortOperationActionPerformed
    //internal methods
    private boolean allEmotionsVoted(){
        for(int i = 0;i<marks.length;i++) 
            if(marks[i]==0) {
                new PopUpAllert(EmotionalSongs.dialoghi.notAllVoted()).setVisible(true);
                return false;
            }
        return true;
    }
    
    private String formatAndCleanString(String stringToFormat){
        if(stringToFormat.equals(new Italiano().songsJudgeCommentRequest())||stringToFormat.equals(new English().songsJudgeCommentRequest())) {
            return "-";
        } else {
            stringToFormat.replace(";", ",");
            stringToFormat.replace("\n", " ");
            stringToFormat.replace("\r", " ");
            stringToFormat.replace("\t", " ");
            if(!stringToFormat.endsWith(".")) stringToFormat+=".";
            return stringToFormat;
        }
    }
    
    /*DEBUGGING*/
    /*
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setSize(800, 800);
        Repository repo = EmotionalSongs.REPOSITORY;
        Song trySong = repo.getBrano(1527);
        frame.add(new GUISongJudgementForm("userIdTryal",trySong.getTag()));
        frame.setVisible(true);
    }
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbortOperation;
    private javax.swing.JButton CompleteOperation;
    private javax.swing.JPanel GeneralDescriptionPane;
    private javax.swing.JLabel amazementDescription;
    private javax.swing.JRadioButton amazementMark1;
    private javax.swing.JRadioButton amazementMark2;
    private javax.swing.JRadioButton amazementMark3;
    private javax.swing.JRadioButton amazementMark4;
    private javax.swing.JRadioButton amazementMark5;
    private javax.swing.JPanel amazementMarksPanel;
    private javax.swing.JTextArea amazementNotes;
    private javax.swing.JPanel amazementPane;
    private javax.swing.JLabel amazementTitle;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel calmnessDescription;
    private javax.swing.JRadioButton calmnessMark1;
    private javax.swing.JRadioButton calmnessMark2;
    private javax.swing.JRadioButton calmnessMark3;
    private javax.swing.JRadioButton calmnessMark4;
    private javax.swing.JRadioButton calmnessMark5;
    private javax.swing.JPanel calmnessMarkPanel;
    private javax.swing.JTextArea calmnessNotes;
    private javax.swing.JPanel calmnessPane;
    private javax.swing.JLabel calmnessTitle;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel joyDescription;
    private javax.swing.JRadioButton joyMark1;
    private javax.swing.JRadioButton joyMark2;
    private javax.swing.JRadioButton joyMark3;
    private javax.swing.JRadioButton joyMark4;
    private javax.swing.JRadioButton joyMark5;
    private javax.swing.JPanel joyMarksPanel;
    private javax.swing.JTextArea joyNotes;
    private javax.swing.JPanel joyPane;
    private javax.swing.JLabel joyTitle;
    private javax.swing.JPanel mainAmazementEmotionPane;
    private javax.swing.JLabel nostalgiaDescription;
    private javax.swing.JRadioButton nostalgiaMark1;
    private javax.swing.JRadioButton nostalgiaMark2;
    private javax.swing.JRadioButton nostalgiaMark3;
    private javax.swing.JRadioButton nostalgiaMark4;
    private javax.swing.JRadioButton nostalgiaMark5;
    private javax.swing.JPanel nostalgiaMarksPanel;
    private javax.swing.JTextArea nostalgiaNotes;
    private javax.swing.JPanel nostalgiaPane;
    private javax.swing.JLabel nostalgiaTitle;
    private javax.swing.JLabel powerDescription;
    private javax.swing.JRadioButton powerMark1;
    private javax.swing.JRadioButton powerMark2;
    private javax.swing.JRadioButton powerMark3;
    private javax.swing.JRadioButton powerMark4;
    private javax.swing.JRadioButton powerMark5;
    private javax.swing.JPanel powerMarksPanel;
    private javax.swing.JTextArea powerNotes;
    private javax.swing.JPanel powerPane;
    private javax.swing.JLabel powerTitle;
    private javax.swing.JLabel sadnessDescription;
    private javax.swing.JRadioButton sadnessMark1;
    private javax.swing.JRadioButton sadnessMark2;
    private javax.swing.JRadioButton sadnessMark3;
    private javax.swing.JRadioButton sadnessMark4;
    private javax.swing.JRadioButton sadnessMark5;
    private javax.swing.JPanel sadnessMarksPanes;
    private javax.swing.JTextArea sadnessNotes;
    private javax.swing.JPanel sadnessPane;
    private javax.swing.JLabel sadnessTitle;
    private javax.swing.JLabel solemnityDescription;
    private javax.swing.JRadioButton solemnityMark1;
    private javax.swing.JRadioButton solemnityMark2;
    private javax.swing.JRadioButton solemnityMark3;
    private javax.swing.JRadioButton solemnityMark4;
    private javax.swing.JRadioButton solemnityMark5;
    private javax.swing.JPanel solemnityMarksPane;
    private javax.swing.JTextArea solemnityNotes;
    private javax.swing.JPanel solemnityPane;
    private javax.swing.JLabel solemnityTitle;
    private javax.swing.JLabel songDataLabel;
    private javax.swing.JLabel tendernessDescription;
    private javax.swing.JRadioButton tendernessMark1;
    private javax.swing.JRadioButton tendernessMark2;
    private javax.swing.JRadioButton tendernessMark3;
    private javax.swing.JRadioButton tendernessMark4;
    private javax.swing.JRadioButton tendernessMark5;
    private javax.swing.JPanel tendernessMarksPanel;
    private javax.swing.JTextArea tendernessNotes;
    private javax.swing.JPanel tendernessPane;
    private javax.swing.JLabel tendernessTitle;
    private javax.swing.JLabel tensionDescription;
    private javax.swing.JRadioButton tensionMark1;
    private javax.swing.JRadioButton tensionMark2;
    private javax.swing.JRadioButton tensionMark3;
    private javax.swing.JRadioButton tensionMark4;
    private javax.swing.JRadioButton tensionMark5;
    private javax.swing.JPanel tensionMarksPanel;
    private javax.swing.JTextArea tensionNotes;
    private javax.swing.JPanel tensionPane;
    private javax.swing.JLabel tensionTitle;
    // End of variables declaration//GEN-END:variables
    private int[] marks = new int[9];
    //amazementMark=>0,solemnityMark=>1,tendernessMark=>2,nostalgiaMark=>3,calmnessMark=>4,powerMark=>5,joyMark=>6,tensionMark=>7,sadnessMark=>8;
    private String[] notes = new String[9];
    //amazementNote => 0,solemnityNote => 1,tendernessNote => 2,nostalgiaNote => 3,calmnessNote => 4,powerNote => 5,joyNote => 6,tensionNote => 7,sadnessNote => 8;
    private String loggedUserId;
    private String songToVoteTag;
    private Song songUnderVotation;
    private SongPanel callerComponent;
    private JFrame container;
}
