/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package emotionalsongs.GUI.Generics;
import emotionalsongs.Utilities;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Megaport
 */
public class GUICreditsPanel extends javax.swing.JPanel {

    /**
     * Creates new form creditsPanel
     */
    public GUICreditsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
@Override
            protected void paintComponent(Graphics g){
                Graphics g2 = g.create();
                g2.drawImage(Utilities.CreditsIcon.getImage(), 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
