//Luca Bolelli - 749137 - VA
//Natanail Danailov Danailov - 739887 - VA
//Alexandru Boitor - 749004 - VA

package emotionalsongs.GUI.Generics;


import java.awt.geom.*;
import javax.swing.*;

/**
 *
 * @author Megaport
 */
public class GUIInitializationFrame extends javax.swing.JFrame {

    /**
     * Creates new form newLoadingFrame
     */
    public GUIInitializationFrame() {
        setUndecorated(true);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        BGLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(new ImageIcon("../EmotionalSongs/Risorse/EmotionalSongsLogo.png").getImage());
        setResizable(false);
        setShape(new RoundRectangle2D.Double(0, 0, 790, 560, 20, 20)
        );
        setSize(new java.awt.Dimension(790, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG.setBackground(new java.awt.Color(0, 0, 0));
        BG.setMaximumSize(new java.awt.Dimension(790, 560));
        BG.setMinimumSize(new java.awt.Dimension(790, 560));

        BGLabel.setBackground(new java.awt.Color(255, 255, 255));
        BGLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGLabel.setIcon(new ImageIcon("../EmotionalSongs/Risorse/LoadingFrameWhite.png"));
        BGLabel.setToolTipText("");
        BGLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BGLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BGLabel.setMaximumSize(new java.awt.Dimension(790, 560));
        BGLabel.setMinimumSize(new java.awt.Dimension(790, 560));
        BGLabel.setOpaque(true);
        BGLabel.setPreferredSize(new java.awt.Dimension(790, 560));
        BGLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel BGLabel;
    // End of variables declaration//GEN-END:variables
}
