package emotionalsongs.GUI.mainWindow;

import emotionalsongs.GUI.Repository.*;
import emotionalsongs.Managers.*;
import java.io.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Megaport
 */
public class GUIMainMenuLeftLogged extends javax.swing.JPanel {
    
    MainFrame mainPage;

    /** Creates new form UnloggedMenu */
    public GUIMainMenuLeftLogged(MainFrame correlated) {
        mainPage = correlated;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        repositoryPanel = new javax.swing.JPanel();
        repositoryButton = new javax.swing.JButton();
        playlistPanel = new javax.swing.JPanel();
        playlistsButton = new javax.swing.JButton();
        createPlaylistPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(22,33,62,160));
        setPreferredSize(new java.awt.Dimension(120, 600));
        setLayout(new java.awt.BorderLayout(0, 5));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,45));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(80, 300));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 300));
        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        repositoryPanel.setBackground(new java.awt.Color(0, 0, 0));
        repositoryPanel.setLayout(new java.awt.BorderLayout());

        repositoryButton.setBackground(new java.awt.Color(15, 52, 96));
        repositoryButton.setForeground(new java.awt.Color(255, 255, 255));
        repositoryButton.setText("Repository");
        repositoryButton.setToolTipText("");
        repositoryButton.setBorder(null);
        repositoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repositoryButtonActionPerformed(evt);
            }
        });
        repositoryPanel.add(repositoryButton, java.awt.BorderLayout.CENTER);

        jPanel2.add(repositoryPanel);

        playlistPanel.setBackground(new java.awt.Color(0, 0, 0));
        playlistPanel.setLayout(new java.awt.BorderLayout());

        playlistsButton.setBackground(new java.awt.Color(15, 52, 96));
        playlistsButton.setForeground(new java.awt.Color(255, 255, 255));
        playlistsButton.setText("Playlist utente");
        playlistsButton.setToolTipText("");
        playlistsButton.setBorder(null);
        playlistsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistsButtonActionPerformed(evt);
            }
        });
        playlistPanel.add(playlistsButton, java.awt.BorderLayout.CENTER);

        jPanel2.add(playlistPanel);

        createPlaylistPanel.setBackground(new java.awt.Color(0, 0, 0));
        createPlaylistPanel.setLayout(new java.awt.BorderLayout());

        createButton.setBackground(new java.awt.Color(15, 52, 96));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Nuova playlist");
        createButton.setToolTipText("");
        createButton.setBorder(null);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        createPlaylistPanel.add(createButton, java.awt.BorderLayout.CENTER);

        jPanel2.add(createPlaylistPanel);

        jPanel3.add(jPanel2, java.awt.BorderLayout.NORTH);

        closeButton.setBackground(new java.awt.Color(255, 0, 51));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Esci");
        closeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, javax.swing.UIManager.getDefaults().getColor("Objects.Red"), javax.swing.UIManager.getDefaults().getColor("Component.custom.borderColor"), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0)));
        closeButton.setOpaque(true);
        closeButton.setPreferredSize(new java.awt.Dimension(75, 50));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(closeButton, java.awt.BorderLayout.PAGE_END);

        profileButton.setBackground(new java.awt.Color(15, 52, 96));
        profileButton.setForeground(new java.awt.Color(255, 255, 255));
        profileButton.setText("Profilo");
        profileButton.setToolTipText("");
        profileButton.setBorder(null);
        profileButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        profileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });
        jPanel3.add(profileButton, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        mainPage.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void repositoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repositoryButtonActionPerformed
        try {
            mainPage.setMainPanel(new GUIRepositoryPanel());
        } catch (IOException ex) {
            ex.getMessage();
        } 
    }//GEN-LAST:event_repositoryButtonActionPerformed

    private void playlistsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistsButtonActionPerformed
        PlayListsManager.getInstance().updatePlaylistsPanel();
    }//GEN-LAST:event_playlistsButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt){
        PlayListsManager.getInstance().startCreation();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel createPlaylistPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel playlistPanel;
    private javax.swing.JButton playlistsButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton repositoryButton;
    private javax.swing.JPanel repositoryPanel;
    // End of variables declaration//GEN-END:variables

}
