/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emotionalsongs.GUIElements;

/**
 *
 * @author natanaild
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LoginLabelPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        UserIDFieldPanel = new javax.swing.JPanel();
        UserIDLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        UserIDField = new javax.swing.JTextField();
        UserIDCheckLabel = new javax.swing.JLabel();
        PasswordFieldPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordCheckLabel = new javax.swing.JLabel();
        LoginButtonsPanel = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AnnullaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        LoginLabelPanel.setLayout(new java.awt.GridLayout(1, 0));

        LoginLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("emotionalsongs/GUIElements/Bundle"); // NOI18N
        LoginLabel.setText(bundle.getString("LoginFrame.LoginLabel.text")); // NOI18N
        LoginLabelPanel.add(LoginLabel);

        getContentPane().add(LoginLabelPanel);

        UserIDFieldPanel.setLayout(new java.awt.GridBagLayout());

        UserIDLabel.setText(bundle.getString("LoginFrame.UserIDLabel.text")); // NOI18N
        UserIDFieldPanel.add(UserIDLabel, new java.awt.GridBagConstraints());
        UserIDFieldPanel.add(jPanel5, new java.awt.GridBagConstraints());

        UserIDField.setText(bundle.getString("LoginFrame.UserIDField.text")); // NOI18N
        UserIDField.setPreferredSize(new java.awt.Dimension(200, 23));
        UserIDFieldPanel.add(UserIDField, new java.awt.GridBagConstraints());

        UserIDCheckLabel.setForeground(new java.awt.Color(255, 0, 0));
        UserIDCheckLabel.setText(bundle.getString("LoginFrame.UserIDCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        UserIDFieldPanel.add(UserIDCheckLabel, gridBagConstraints);

        getContentPane().add(UserIDFieldPanel);

        PasswordFieldPanel.setLayout(new java.awt.GridBagLayout());

        PasswordLabel.setText(bundle.getString("LoginFrame.PasswordLabel.text")); // NOI18N
        PasswordFieldPanel.add(PasswordLabel, new java.awt.GridBagConstraints());
        PasswordFieldPanel.add(jPanel6, new java.awt.GridBagConstraints());

        PasswordField.setText(bundle.getString("LoginFrame.PasswordField.text_1")); // NOI18N
        PasswordField.setPreferredSize(new java.awt.Dimension(200, 23));
        PasswordFieldPanel.add(PasswordField, new java.awt.GridBagConstraints());

        PasswordCheckLabel.setForeground(new java.awt.Color(255, 0, 0));
        PasswordCheckLabel.setText(bundle.getString("LoginFrame.PasswordCheckLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        PasswordFieldPanel.add(PasswordCheckLabel, gridBagConstraints);

        getContentPane().add(PasswordFieldPanel);

        LoginButtonsPanel.setLayout(new java.awt.GridBagLayout());

        LoginButton.setText(bundle.getString("LoginFrame.LoginButton.text")); // NOI18N
        LoginButtonsPanel.add(LoginButton, new java.awt.GridBagConstraints());
        LoginButtonsPanel.add(jPanel1, new java.awt.GridBagConstraints());

        AnnullaButton.setText(bundle.getString("LoginFrame.AnnullaButton.text")); // NOI18N
        LoginButtonsPanel.add(AnnullaButton, new java.awt.GridBagConstraints());

        getContentPane().add(LoginButtonsPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullaButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginButtonsPanel;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginLabelPanel;
    private javax.swing.JLabel PasswordCheckLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel PasswordFieldPanel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel UserIDCheckLabel;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JPanel UserIDFieldPanel;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
