/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package emotionalsongs.GUIElements;

/**
 *
 * @author natanaild
 */
public class MenuButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuButtonPanel
     */
    public MenuButtonPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WestButtonsMenuPanel = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        Button2 = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        Button3 = new javax.swing.JButton();
        Panel4 = new javax.swing.JPanel();
        Button4 = new javax.swing.JButton();
        Panel5 = new javax.swing.JPanel();
        Button5 = new javax.swing.JButton();
        Panel6 = new javax.swing.JPanel();
        Button6 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(160, 561));

        WestButtonsMenuPanel.setPreferredSize(new java.awt.Dimension(160, 571));
        WestButtonsMenuPanel.setLayout(new java.awt.GridLayout(8, 1));

        Panel1.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("emotionalsongs/GUIElements/Bundle"); // NOI18N
        Button1.setText(bundle.getString("MenuButtonPanel.Button1.text")); // NOI18N
        Panel1.add(Button1);

        WestButtonsMenuPanel.add(Panel1);

        Panel2.setLayout(new java.awt.GridLayout(1, 0));

        Button2.setText(bundle.getString("MenuButtonPanel.Button2.text")); // NOI18N
        Panel2.add(Button2);

        WestButtonsMenuPanel.add(Panel2);

        Panel3.setLayout(new java.awt.GridLayout(1, 0));

        Button3.setText(bundle.getString("MenuButtonPanel.Button3.text")); // NOI18N
        Panel3.add(Button3);

        WestButtonsMenuPanel.add(Panel3);

        Panel4.setLayout(new java.awt.GridLayout(1, 0));

        Button4.setText(bundle.getString("MenuButtonPanel.Button4.text")); // NOI18N
        Panel4.add(Button4);

        WestButtonsMenuPanel.add(Panel4);

        Panel5.setLayout(new java.awt.GridLayout(1, 0));

        Button5.setText(bundle.getString("MenuButtonPanel.Button5.text")); // NOI18N
        Panel5.add(Button5);

        WestButtonsMenuPanel.add(Panel5);

        Panel6.setLayout(new java.awt.GridLayout(1, 0));

        Button6.setText(bundle.getString("MenuButtonPanel.Button6.text")); // NOI18N
        Panel6.add(Button6);

        WestButtonsMenuPanel.add(Panel6);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(WestButtonsMenuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 561, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(WestButtonsMenuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 561, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel6;
    private javax.swing.JPanel WestButtonsMenuPanel;
    // End of variables declaration//GEN-END:variables
}
